import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import Icon from '@/components/ui/icon';

interface SensorData {
  id: string;
  name: string;
  location: string;
  value: number;
  unit: string;
  status: 'normal' | 'warning' | 'critical';
  lastUpdate: string;
}

interface AutoAlert {
  id: string;
  title: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  timestamp: string;
  location: string;
  status: 'active' | 'acknowledged' | 'resolved';
  autoGenerated: boolean;
}

interface ComplianceReport {
  id: string;
  title: string;
  type: 'daily' | 'weekly' | 'monthly';
  generatedAt: string;
  status: 'generated' | 'processing' | 'ready';
  compliance: number;
}

interface NotificationChannel {
  id: string;
  name: string;
  type: 'telegram' | 'sms' | 'email' | 'webhook';
  status: 'active' | 'inactive' | 'error';
  lastUsed: string;
  config: {
    endpoint?: string;
    recipients?: string[];
    template?: string;
  };
}

interface MLPrediction {
  id: string;
  type: 'incident_risk' | 'equipment_failure' | 'safety_trend';
  confidence: number;
  prediction: string;
  timeframe: string;
  factors: string[];
  createdAt: string;
}

interface Integration {
  id: string;
  name: string;
  type: '1c' | 'sap' | 'erp' | 'external_api';
  status: 'connected' | 'disconnected' | 'syncing';
  lastSync: string;
  dataExchanged: number;
}

interface UserRole {
  id: string;
  name: string;
  level: 'operator' | 'engineer' | 'manager' | 'admin';
  permissions: string[];
  dashboardConfig: {
    widgets: string[];
    alertLevel: 'all' | 'critical' | 'none';
    dataAccess: string[];
  };
}

interface User {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  role: UserRole;
  isOnline: boolean;
  lastActivity: string;
}

interface QuickAction {
  id: string;
  title: string;
  description: string;
  type: 'emergency' | 'maintenance' | 'report' | 'notification';
  icon: string;
  requiresConfirmation: boolean;
  userLevels: string[];
}

interface BackupConfig {
  id: string;
  name: string;
  type: 'full' | 'incremental' | 'differential';
  schedule: 'daily' | 'weekly' | 'monthly' | 'custom';
  status: 'active' | 'paused' | 'error';
  lastBackup: string;
  nextBackup: string;
  size: string;
  retention: number;
  location: string;
}

interface RestorePoint {
  id: string;
  name: string;
  type: 'manual' | 'automatic' | 'critical';
  createdAt: string;
  size: string;
  integrity: 'verified' | 'corrupted' | 'unknown';
  description: string;
  dataTypes: string[];
}

interface SecurityAudit {
  id: string;
  title: string;
  type: 'access_control' | 'data_integrity' | 'system_health' | 'compliance';
  status: 'completed' | 'running' | 'failed' | 'scheduled';
  severity: 'low' | 'medium' | 'high' | 'critical';
  startTime: string;
  endTime?: string;
  findings: {
    issues: number;
    warnings: number;
    passed: number;
  };
  recommendations: string[];
}

interface SystemIntegrity {
  id: string;
  component: string;
  status: 'healthy' | 'warning' | 'critical' | 'offline';
  lastCheck: string;
  uptime: string;
  performance: number;
  issues: string[];
  metrics: {
    cpu: number;
    memory: number;
    disk: number;
    network: number;
  };
}

const Index = () => {
  const [activeTab, setActiveTab] = useState('monitoring');
  const [isMobile, setIsMobile] = useState(false);
  const [currentUser, setCurrentUser] = useState<User>({
    id: '1',
    name: 'Александр Иванов',
    email: 'a.ivanov@ht-systems.ru',
    avatar: '/avatar-placeholder.jpg',
    role: {
      id: '1',
      name: 'Главный инженер',
      level: 'admin',
      permissions: ['view_all', 'edit_all', 'manage_users', 'system_config'],
      dashboardConfig: {
        widgets: ['monitoring', 'alerts', 'analytics', 'reports'],
        alertLevel: 'all',
        dataAccess: ['all_sensors', 'all_departments', 'financial_data']
      }
    },
    isOnline: true,
    lastActivity: '2024-01-28 14:30:00'
  });

  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    
    checkMobile();
    window.addEventListener('resize', checkMobile);
    
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  const [realTimeData, setRealTimeData] = useState<SensorData[]>([
    {
      id: '1',
      name: 'Датчик загазованности',
      location: 'Цех №1, участок А',
      value: 0.02,
      unit: 'ppm',
      status: 'normal',
      lastUpdate: new Date().toISOString()
    },
    {
      id: '2', 
      name: 'Уровень шума',
      location: 'Цех №2, линия В',
      value: 85,
      unit: 'дБ',
      status: 'warning',
      lastUpdate: new Date().toISOString()
    },
    {
      id: '3',
      name: 'Температура',
      location: 'Склад материалов',
      value: 45,
      unit: '°C',
      status: 'critical',
      lastUpdate: new Date().toISOString()
    },
    {
      id: '4',
      name: 'Освещенность',
      location: 'Офисная зона',
      value: 520,
      unit: 'лк',
      status: 'normal',
      lastUpdate: new Date().toISOString()
    }
  ]);

  const [autoAlerts] = useState<AutoAlert[]>([
    {
      id: '1',
      title: 'Превышение допустимого уровня шума',
      severity: 'high',
      timestamp: '2024-01-28 14:23:15',
      location: 'Цех №2, линия В',
      status: 'active',
      autoGenerated: true
    },
    {
      id: '2',
      title: 'Критическое превышение температуры',
      severity: 'critical',
      timestamp: '2024-01-28 14:15:42',
      location: 'Склад материалов',
      status: 'acknowledged',
      autoGenerated: true
    },
    {
      id: '3',
      title: 'Обнаружение газа выше нормы',
      severity: 'medium',
      timestamp: '2024-01-28 13:45:22',
      location: 'Цех №1, участок А',
      status: 'resolved',
      autoGenerated: true
    }
  ]);

  const [reports] = useState<ComplianceReport[]>([
    {
      id: '1',
      title: 'Ежедневный отчет по безопасности',
      type: 'daily',
      generatedAt: '2024-01-28 09:00:00',
      status: 'ready',
      compliance: 94
    },
    {
      id: '2',
      title: 'Недельный анализ инцидентов',
      type: 'weekly',
      generatedAt: '2024-01-28 08:30:00',
      status: 'ready',
      compliance: 89
    },
    {
      id: '3',
      title: 'Месячный отчет соответствия',
      type: 'monthly',
      generatedAt: '2024-01-28 07:00:00',
      status: 'processing',
      compliance: 0
    }
  ]);

  const [notifications] = useState<NotificationChannel[]>([
    {
      id: '1',
      name: 'Критические алерты Telegram',
      type: 'telegram',
      status: 'active',
      lastUsed: '2024-01-28 14:23:15',
      config: {
        endpoint: '@safety_alerts_bot',
        recipients: ['Администратор', 'Начальник охраны труда']
      }
    },
    {
      id: '2',
      name: 'SMS экстренные уведомления',
      type: 'sms',
      status: 'active',
      lastUsed: '2024-01-28 14:15:42',
      config: {
        recipients: ['+7 XXX XXX-XX-01', '+7 XXX XXX-XX-02']
      }
    },
    {
      id: '3',
      name: 'Email отчеты',
      type: 'email',
      status: 'active',
      lastUsed: '2024-01-28 09:00:00',
      config: {
        recipients: ['safety@ht-systems.ru', 'admin@ht-systems.ru']
      }
    },
    {
      id: '4',
      name: 'Интеграция с 1С',
      type: 'webhook',
      status: 'inactive',
      lastUsed: '2024-01-27 18:30:00',
      config: {
        endpoint: 'https://1c.ht-systems.ru/api/safety'
      }
    }
  ]);

  const [mlPredictions] = useState<MLPrediction[]>([
    {
      id: '1',
      type: 'incident_risk',
      confidence: 87,
      prediction: 'Высокий риск травмы в цехе №2',
      timeframe: 'Ближайшие 48 часов',
      factors: ['Повышенный уровень шума', 'Нарушение графика обслуживания'],
      createdAt: '2024-01-28 14:30:00'
    },
    {
      id: '2',
      type: 'equipment_failure',
      confidence: 92,
      prediction: 'Отказ системы вентиляции',
      timeframe: 'Ближайшая неделя',
      factors: ['Превышение рабочих часов', 'Отклонения в вибрации'],
      createdAt: '2024-01-28 13:45:00'
    },
    {
      id: '3',
      type: 'safety_trend',
      confidence: 78,
      prediction: 'Ухудшение показателей безопасности',
      timeframe: 'Следующий месяц',
      factors: ['Увеличение нагрузки', 'Недостаточное обучение'],
      createdAt: '2024-01-28 12:15:00'
    }
  ]);

  const [integrations] = useState<Integration[]>([
    {
      id: '1',
      name: '1С:Предприятие',
      type: '1c',
      status: 'connected',
      lastSync: '2024-01-28 14:00:00',
      dataExchanged: 1247
    },
    {
      id: '2',
      name: 'SAP ERP',
      type: 'sap',
      status: 'syncing',
      lastSync: '2024-01-28 13:30:00',
      dataExchanged: 892
    },
    {
      id: '3',
      name: 'Система контроля доступа',
      type: 'external_api',
      status: 'connected',
      lastSync: '2024-01-28 14:25:00',
      dataExchanged: 345
    }
  ]);

  const [backupConfigs] = useState<BackupConfig[]>([
    {
      id: '1',
      name: 'Полный бэкап системы',
      type: 'full',
      schedule: 'weekly',
      status: 'active',
      lastBackup: '2024-01-28 02:00:00',
      nextBackup: '2024-02-04 02:00:00',
      size: '2.4 GB',
      retention: 12,
      location: 'backup-server-01/full'
    },
    {
      id: '2',
      name: 'Инкрементальный бэкап',
      type: 'incremental',
      schedule: 'daily',
      status: 'active',
      lastBackup: '2024-01-28 23:00:00',
      nextBackup: '2024-01-29 23:00:00',
      size: '156 MB',
      retention: 30,
      location: 'backup-server-01/incremental'
    },
    {
      id: '3',
      name: 'Критические данные',
      type: 'differential',
      schedule: 'daily',
      status: 'active',
      lastBackup: '2024-01-28 18:00:00',
      nextBackup: '2024-01-29 18:00:00',
      size: '245 MB',
      retention: 60,
      location: 'backup-server-02/critical'
    },
    {
      id: '4',
      name: 'Архив отчетов',
      type: 'full',
      schedule: 'monthly',
      status: 'paused',
      lastBackup: '2024-01-01 03:00:00',
      nextBackup: '2024-02-01 03:00:00',
      size: '890 MB',
      retention: 36,
      location: 'archive-server/reports'
    }
  ]);

  const [restorePoints] = useState<RestorePoint[]>([
    {
      id: '1',
      name: 'Система до обновления ML',
      type: 'manual',
      createdAt: '2024-01-27 14:30:00',
      size: '2.1 GB',
      integrity: 'verified',
      description: 'Точка восстановления перед внедрением новой ML модели',
      dataTypes: ['sensors', 'ml_models', 'user_settings', 'alerts']
    },
    {
      id: '2',
      name: 'Автобэкап 28.01.2024',
      type: 'automatic',
      createdAt: '2024-01-28 02:00:15',
      size: '2.4 GB',
      integrity: 'verified',
      description: 'Еженедельный автоматический бэкап системы',
      dataTypes: ['all_data', 'configurations', 'logs', 'reports']
    },
    {
      id: '3',
      name: 'Критический инцидент',
      type: 'critical',
      createdAt: '2024-01-28 14:15:42',
      size: '1.8 GB',
      integrity: 'verified',
      description: 'Состояние системы на момент критического алерта',
      dataTypes: ['sensors', 'alerts', 'user_actions', 'system_logs']
    },
    {
      id: '4',
      name: 'Поврежденный бэкап',
      type: 'automatic',
      createdAt: '2024-01-26 02:00:00',
      size: '2.2 GB',
      integrity: 'corrupted',
      description: 'Бэкап с ошибками целостности данных',
      dataTypes: ['partial_data']
    }
  ]);

  const [securityAudits] = useState<SecurityAudit[]>([
    {
      id: '1',
      title: 'Аудит системы доступа',
      type: 'access_control',
      status: 'completed',
      severity: 'medium',
      startTime: '2024-01-28 09:00:00',
      endTime: '2024-01-28 09:45:23',
      findings: {
        issues: 2,
        warnings: 7,
        passed: 48
      },
      recommendations: [
        'Обновить пароли для служебных аккаунтов',
        'Включить двухфакторную аутентификацию для администраторов',
        'Настроить автоматическую блокировку неактивных сессий'
      ]
    },
    {
      id: '2',
      title: 'Проверка целостности данных',
      type: 'data_integrity',
      status: 'completed',
      severity: 'low',
      startTime: '2024-01-28 10:30:00',
      endTime: '2024-01-28 11:15:12',
      findings: {
        issues: 0,
        warnings: 3,
        passed: 156
      },
      recommendations: [
        'Настроить автоматическую проверку контрольных сумм',
        'Увеличить частоту проверки критических датчиков'
      ]
    },
    {
      id: '3',
      title: 'Аудит соответствия требованиям',
      type: 'compliance',
      status: 'running',
      severity: 'high',
      startTime: '2024-01-28 14:00:00',
      findings: {
        issues: 0,
        warnings: 0,
        passed: 23
      },
      recommendations: []
    },
    {
      id: '4',
      title: 'Проверка работоспособности',
      type: 'system_health',
      status: 'scheduled',
      severity: 'low',
      startTime: '2024-01-29 02:00:00',
      findings: {
        issues: 0,
        warnings: 0,
        passed: 0
      },
      recommendations: []
    }
  ]);

  const [systemIntegrity] = useState<SystemIntegrity[]>([
    {
      id: '1',
      component: 'База данных',
      status: 'healthy',
      lastCheck: '2024-01-28 14:30:00',
      uptime: '99.97%',
      performance: 94,
      issues: [],
      metrics: {
        cpu: 45,
        memory: 62,
        disk: 78,
        network: 23
      }
    },
    {
      id: '2',
      component: 'ML сервис',
      status: 'warning',
      lastCheck: '2024-01-28 14:29:45',
      uptime: '99.89%',
      performance: 87,
      issues: ['Высокое потребление памяти', 'Периодические задержки обработки'],
      metrics: {
        cpu: 78,
        memory: 89,
        disk: 45,
        network: 67
      }
    },
    {
      id: '3',
      component: 'Система уведомлений',
      status: 'healthy',
      lastCheck: '2024-01-28 14:28:12',
      uptime: '99.95%',
      performance: 98,
      issues: [],
      metrics: {
        cpu: 12,
        memory: 34,
        disk: 23,
        network: 45
      }
    },
    {
      id: '4',
      component: 'Интеграции 1С',
      status: 'critical',
      lastCheck: '2024-01-28 14:15:00',
      uptime: '89.12%',
      performance: 45,
      issues: ['Потеря соединения', 'Ошибки синхронизации', 'Превышение тайм-аута'],
      metrics: {
        cpu: 23,
        memory: 45,
        disk: 67,
        network: 12
      }
    }
  ]);

  const [userRoles] = useState<UserRole[]>([
    {
      id: '1',
      name: 'Администратор',
      level: 'admin',
      permissions: ['view_all', 'edit_all', 'manage_users', 'system_config'],
      dashboardConfig: {
        widgets: ['monitoring', 'alerts', 'analytics', 'reports', 'ml', 'integrations'],
        alertLevel: 'all',
        dataAccess: ['all_sensors', 'all_departments', 'financial_data']
      }
    },
    {
      id: '2',
      name: 'Главный инженер',
      level: 'engineer',
      permissions: ['view_all', 'edit_sensors', 'manage_alerts'],
      dashboardConfig: {
        widgets: ['monitoring', 'alerts', 'analytics'],
        alertLevel: 'all',
        dataAccess: ['all_sensors', 'technical_data']
      }
    },
    {
      id: '3',
      name: 'Оператор',
      level: 'operator',
      permissions: ['view_monitoring', 'acknowledge_alerts'],
      dashboardConfig: {
        widgets: ['monitoring', 'alerts'],
        alertLevel: 'critical',
        dataAccess: ['assigned_sensors']
      }
    },
    {
      id: '4',
      name: 'Руководитель',
      level: 'manager',
      permissions: ['view_reports', 'view_analytics'],
      dashboardConfig: {
        widgets: ['analytics', 'reports'],
        alertLevel: 'critical',
        dataAccess: ['summary_data', 'financial_data']
      }
    }
  ]);

  const [quickActions] = useState<QuickAction[]>([
    {
      id: '1',
      title: 'Экстренная остановка',
      description: 'Остановить все оборудование',
      type: 'emergency',
      icon: 'AlertTriangle',
      requiresConfirmation: true,
      userLevels: ['admin', 'engineer']
    },
    {
      id: '2',
      title: 'Оповещение персонала',
      description: 'Отправить уведомление всем',
      type: 'notification',
      icon: 'Megaphone',
      requiresConfirmation: true,
      userLevels: ['admin', 'manager']
    },
    {
      id: '3',
      title: 'Создать отчет',
      description: 'Генерация экстренного отчета',
      type: 'report',
      icon: 'FileText',
      requiresConfirmation: false,
      userLevels: ['admin', 'manager', 'engineer']
    },
    {
      id: '4',
      title: 'Запланировать ТО',
      description: 'Создать задачу на обслуживание',
      type: 'maintenance',
      icon: 'Wrench',
      requiresConfirmation: false,
      userLevels: ['admin', 'engineer']
    }
  ]);

  // Симуляция обновления данных в реальном времени
  useEffect(() => {
    const interval = setInterval(() => {
      setRealTimeData(prev => prev.map(sensor => ({
        ...sensor,
        value: sensor.value + (Math.random() - 0.5) * 0.1,
        lastUpdate: new Date().toISOString()
      })));
    }, 5000);

    return () => clearInterval(interval);
  }, []);

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'normal': return 'text-green-600 bg-green-100';
      case 'warning': return 'text-yellow-600 bg-yellow-100';
      case 'critical': return 'text-red-600 bg-red-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'low': return 'bg-blue-100 text-blue-800';
      case 'medium': return 'bg-yellow-100 text-yellow-800';
      case 'high': return 'bg-orange-100 text-orange-800';
      case 'critical': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getAlertStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-red-100 text-red-800';
      case 'acknowledged': return 'bg-blue-100 text-blue-800';
      case 'resolved': return 'bg-green-100 text-green-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getNotificationStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'text-green-600 bg-green-100';
      case 'inactive': return 'text-gray-600 bg-gray-100';
      case 'error': return 'text-red-600 bg-red-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const getIntegrationStatusColor = (status: string) => {
    switch (status) {
      case 'connected': return 'text-green-600 bg-green-100';
      case 'disconnected': return 'text-red-600 bg-red-100';
      case 'syncing': return 'text-blue-600 bg-blue-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 90) return 'text-green-600';
    if (confidence >= 70) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getActionColor = (type: string) => {
    switch (type) {
      case 'emergency': return 'bg-red-600 hover:bg-red-700 text-white';
      case 'notification': return 'bg-blue-600 hover:bg-blue-700 text-white';
      case 'report': return 'bg-green-600 hover:bg-green-700 text-white';
      case 'maintenance': return 'bg-orange-600 hover:bg-orange-700 text-white';
      default: return 'bg-gray-600 hover:bg-gray-700 text-white';
    }
  };

  const hasPermission = (permission: string) => {
    return currentUser.role.permissions.includes(permission) || currentUser.role.permissions.includes('view_all');
  };

  const canAccessWidget = (widget: string) => {
    return currentUser.role.dashboardConfig.widgets.includes(widget);
  };

  const availableActions = quickActions.filter(action => 
    action.userLevels.includes(currentUser.role.level)
  );

  const getBackupStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'text-green-600 bg-green-100';
      case 'paused': return 'text-yellow-600 bg-yellow-100';
      case 'error': return 'text-red-600 bg-red-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const getIntegrityColor = (integrity: string) => {
    switch (integrity) {
      case 'verified': return 'text-green-600 bg-green-100';
      case 'corrupted': return 'text-red-600 bg-red-100';
      case 'unknown': return 'text-yellow-600 bg-yellow-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const getAuditStatusColor = (status: string) => {
    switch (status) {
      case 'completed': return 'text-green-600 bg-green-100';
      case 'running': return 'text-blue-600 bg-blue-100';
      case 'failed': return 'text-red-600 bg-red-100';
      case 'scheduled': return 'text-gray-600 bg-gray-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const getSystemStatusColor = (status: string) => {
    switch (status) {
      case 'healthy': return 'text-green-600 bg-green-100';
      case 'warning': return 'text-yellow-600 bg-yellow-100';
      case 'critical': return 'text-red-600 bg-red-100';
      case 'offline': return 'text-gray-600 bg-gray-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const getTotalBackupSize = () => {
    const sizes = backupConfigs.map(config => {
      const sizeStr = config.size;
      const value = parseFloat(sizeStr);
      const unit = sizeStr.includes('GB') ? 1024 : 1;
      return value * unit;
    });
    const totalMB = sizes.reduce((acc, size) => acc + size, 0);
    return totalMB > 1024 ? `${(totalMB / 1024).toFixed(1)} GB` : `${totalMB.toFixed(0)} MB`;
  };

  const getSystemHealthScore = () => {
    const healthyCount = systemIntegrity.filter(s => s.status === 'healthy').length;
    return Math.round((healthyCount / systemIntegrity.length) * 100);
  };

  const activeAlerts = autoAlerts.filter(alert => alert.status === 'active').length;
  const criticalSensors = realTimeData.filter(sensor => sensor.status === 'critical').length;
  const averageCompliance = Math.round(reports.filter(r => r.compliance > 0).reduce((acc, r) => acc + r.compliance, 0) / reports.filter(r => r.compliance > 0).length);
  const activeNotifications = notifications.filter(n => n.status === 'active').length;
  const connectedIntegrations = integrations.filter(i => i.status === 'connected').length;

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Mobile Header */}
      {isMobile && (
        <div className="bg-white border-b border-gray-200 px-4 py-3 flex items-center justify-between sticky top-0 z-50">
          <div className="flex items-center space-x-3">
            <Avatar className="h-8 w-8">
              <AvatarImage src={currentUser.avatar} />
              <AvatarFallback>{currentUser.name.split(' ').map(n => n[0]).join('')}</AvatarFallback>
            </Avatar>
            <div>
              <div className="font-medium text-sm">{currentUser.name}</div>
              <div className="text-xs text-gray-500">{currentUser.role.name}</div>
            </div>
          </div>
          <div className="flex items-center space-x-2">
            <Sheet>
              <SheetTrigger asChild>
                <Button variant="outline" size="sm">
                  <Icon name="Zap" className="h-4 w-4" />
                </Button>
              </SheetTrigger>
              <SheetContent side="bottom" className="h-[80vh]">
                <SheetHeader>
                  <SheetTitle>Быстрые действия</SheetTitle>
                  <SheetDescription>
                    Оперативное управление системой
                  </SheetDescription>
                </SheetHeader>
                <div className="grid grid-cols-1 gap-4 mt-6">
                  {availableActions.map((action) => (
                    <Button
                      key={action.id}
                      className={`${getActionColor(action.type)} h-16 flex-col space-y-1`}
                      onClick={() => {
                        if (action.requiresConfirmation) {
                          if (confirm(`Вы уверены, что хотите ${action.title.toLowerCase()}?`)) {
                            console.log(`Выполняем ${action.title}`);
                          }
                        } else {
                          console.log(`Выполняем ${action.title}`);
                        }
                      }}
                    >
                      <Icon name={action.icon as any} className="h-6 w-6" />
                      <div className="text-center">
                        <div className="font-medium">{action.title}</div>
                        <div className="text-xs opacity-90">{action.description}</div>
                      </div>
                    </Button>
                  ))}
                </div>
              </SheetContent>
            </Sheet>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline" size="sm">
                  <Icon name="Menu" className="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-56">
                <DropdownMenuLabel>Меню</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <Icon name="User" className="mr-2 h-4 w-4" />
                  Профиль
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Icon name="Settings" className="mr-2 h-4 w-4" />
                  Настройки
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Icon name="Shield" className="mr-2 h-4 w-4" />
                  Безопасность
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <Icon name="LogOut" className="mr-2 h-4 w-4" />
                  Выйти
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      )}

      <div className={`max-w-7xl mx-auto ${isMobile ? 'p-4' : 'p-6'}`}>
        {/* Header */}
        {!isMobile && (
          <div className="mb-8 flex justify-between items-start">
            <div>
              <h1 className="text-4xl font-bold text-gray-900 mb-2">
                АСУБТ - Автоматизированная система управления безопасностью труда
              </h1>
              <p className="text-lg text-gray-600">
                Комплексный мониторинг и управление системами безопасности промышленного предприятия
              </p>
            </div>
            <div className="flex items-center space-x-4">
              <div className="text-right">
                <div className="text-sm text-gray-500">Online: {currentUser.name}</div>
                <div className="text-xs text-gray-400">{currentUser.role.name}</div>
              </div>
              <Avatar>
                <AvatarImage src={currentUser.avatar} />
                <AvatarFallback>{currentUser.name.split(' ').map(n => n[0]).join('')}</AvatarFallback>
              </Avatar>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline">
                    <Icon name="Menu" className="h-4 w-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-56">
                  <DropdownMenuLabel>Меню пользователя</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <Icon name="User" className="mr-2 h-4 w-4" />
                    Профиль
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Icon name="Settings" className="mr-2 h-4 w-4" />
                    Настройки
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Icon name="Shield" className="mr-2 h-4 w-4" />
                    Управление ролями
                  </DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <Icon name="LogOut" className="mr-2 h-4 w-4" />
                    Выйти
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        )}

        {/* Critical Alerts Banner */}
        {activeAlerts > 0 && (
          <Alert className="mb-6 border-red-200 bg-red-50">
            <Icon name="AlertTriangle" className="h-4 w-4 text-red-600" />
            <AlertTitle className="text-red-800">Критические уведомления</AlertTitle>
            <AlertDescription className="text-red-700">
              Обнаружено {activeAlerts} активных критических уведомлений, требующих немедленного внимания.
              <Button variant="link" className="p-0 h-auto text-red-700 underline ml-2">
                Просмотреть все
              </Button>
            </AlertDescription>
          </Alert>
        )}

        {/* Dashboard Overview */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Активные датчики</CardTitle>
              <Icon name="Wifi" className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-primary">{realTimeData.length}</div>
              <p className="text-xs text-muted-foreground mt-1">
                В сети
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Критические</CardTitle>
              <Icon name="AlertCircle" className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-red-600">{criticalSensors}</div>
              <p className="text-xs text-muted-foreground mt-1">
                Состояния
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Алерты</CardTitle>
              <Icon name="Bell" className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-orange-600">{activeAlerts}</div>
              <p className="text-xs text-muted-foreground mt-1">
                Активные
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Уведомления</CardTitle>
              <Icon name="MessageSquare" className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-blue-600">{activeNotifications}</div>
              <p className="text-xs text-muted-foreground mt-1">
                Каналов
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Интеграции</CardTitle>
              <Icon name="Plug" className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-purple-600">{connectedIntegrations}</div>
              <p className="text-xs text-muted-foreground mt-1">
                Подключено
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Соответствие</CardTitle>
              <Icon name="TrendingUp" className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-green-600">{averageCompliance}%</div>
              <p className="text-xs text-muted-foreground mt-1">
                Нормам
              </p>
            </CardContent>
          </Card>
        </div>

        <Tabs defaultValue="monitoring" className="space-y-6">
          <TabsList className={`grid w-full ${isMobile ? 'grid-cols-3' : 'grid-cols-7'}`}>
            {canAccessWidget('monitoring') && (
              <TabsTrigger value="monitoring" className="flex items-center space-x-1">
                <Icon name="Activity" className="h-4 w-4" />
                <span className={isMobile ? "text-xs" : "hidden sm:inline"}>Мониторинг</span>
              </TabsTrigger>
            )}
            {canAccessWidget('alerts') && (
              <TabsTrigger value="alerts" className="flex items-center space-x-1">
                <Icon name="Bell" className="h-4 w-4" />
                <span className={isMobile ? "text-xs" : "hidden sm:inline"}>Алерты</span>
              </TabsTrigger>
            )}
            {canAccessWidget('notifications') && hasPermission('manage_alerts') && (
              <TabsTrigger value="notifications" className="flex items-center space-x-1">
                <Icon name="MessageSquare" className="h-4 w-4" />
                <span className={isMobile ? "text-xs" : "hidden sm:inline"}>Уведомления</span>
              </TabsTrigger>
            )}
            {canAccessWidget('ml') && hasPermission('view_all') && (
              <TabsTrigger value="ml" className="flex items-center space-x-1">
                <Icon name="Brain" className="h-4 w-4" />
                <span className={isMobile ? "text-xs" : "hidden sm:inline"}>ML</span>
              </TabsTrigger>
            )}
            {canAccessWidget('integrations') && hasPermission('system_config') && (
              <TabsTrigger value="integrations" className="flex items-center space-x-1">
                <Icon name="Plug" className="h-4 w-4" />
                <span className={isMobile ? "text-xs" : "hidden sm:inline"}>Интеграции</span>
              </TabsTrigger>
            )}
            {canAccessWidget('analytics') && (
              <TabsTrigger value="analytics" className="flex items-center space-x-1">
                <Icon name="BarChart3" className="h-4 w-4" />
                <span className={isMobile ? "text-xs" : "hidden sm:inline"}>Аналитика</span>
              </TabsTrigger>
            )}
            {hasPermission('manage_users') && (
              <TabsTrigger value="roles" className="flex items-center space-x-1">
                <Icon name="Users" className="h-4 w-4" />
                <span className={isMobile ? "text-xs" : "hidden sm:inline"}>Роли</span>
              </TabsTrigger>
            )}
            {hasPermission('system_config') && (
              <TabsTrigger value="backup" className="flex items-center space-x-1">
                <Icon name="HardDrive" className="h-4 w-4" />
                <span className={isMobile ? "text-xs" : "hidden sm:inline"}>Бэкапы</span>
              </TabsTrigger>
            )}
            {hasPermission('view_all') && (
              <TabsTrigger value="audit" className="flex items-center space-x-1">
                <Icon name="ShieldCheck" className="h-4 w-4" />
                <span className={isMobile ? "text-xs" : "hidden sm:inline"}>Аудит</span>
              </TabsTrigger>
            )}
          </TabsList>

          {/* Real-time Monitoring */}
          <TabsContent value="monitoring" className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-bold text-gray-900">
                Мониторинг в реальном времени
              </h2>
              <div className="flex items-center space-x-2">
                <Button variant="outline" size="sm">
                  <Icon name="Download" className="h-4 w-4 mr-2" />
                  Экспорт данных
                </Button>
                <Button variant="outline" size="sm">
                  <Icon name="RefreshCw" className="h-4 w-4 mr-2" />
                  Обновить
                </Button>
              </div>
            </div>

            <div className="grid gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Показания датчиков</CardTitle>
                  <CardDescription>
                    Данные обновляются автоматически каждые 5 секунд
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Датчик</TableHead>
                        <TableHead>Местоположение</TableHead>
                        <TableHead>Значение</TableHead>
                        <TableHead>Статус</TableHead>
                        <TableHead>Обновлено</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {realTimeData.map((sensor) => (
                        <TableRow key={sensor.id}>
                          <TableCell className="font-medium">{sensor.name}</TableCell>
                          <TableCell>{sensor.location}</TableCell>
                          <TableCell>
                            <span className="font-mono">
                              {sensor.value.toFixed(2)} {sensor.unit}
                            </span>
                          </TableCell>
                          <TableCell>
                            <Badge className={getStatusColor(sensor.status)}>
                              {sensor.status}
                            </Badge>
                          </TableCell>
                          <TableCell className="text-sm text-gray-500">
                            {new Date(sensor.lastUpdate).toLocaleTimeString('ru-RU')}
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          {/* Auto Alerts */}
          <TabsContent value="alerts" className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-bold text-gray-900">
                Автоматические уведомления
              </h2>
              <Button>
                <Icon name="Settings" className="h-4 w-4 mr-2" />
                Настроить правила
              </Button>
            </div>

            <div className="grid gap-4">
              {autoAlerts.map((alert) => (
                <Card key={alert.id} className={`border-l-4 ${
                  alert.severity === 'critical' ? 'border-l-red-500' :
                  alert.severity === 'high' ? 'border-l-orange-500' :
                  alert.severity === 'medium' ? 'border-l-yellow-500' :
                  'border-l-blue-500'
                }`}>
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <Icon name="Zap" className="h-5 w-5 text-primary" />
                        <CardTitle className="text-lg">{alert.title}</CardTitle>
                      </div>
                      <div className="flex items-center space-x-2">
                        <Badge className={getSeverityColor(alert.severity)}>
                          {alert.severity}
                        </Badge>
                        <Badge className={getAlertStatusColor(alert.status)}>
                          {alert.status}
                        </Badge>
                        {alert.autoGenerated && (
                          <Badge variant="outline" className="text-xs">
                            Авто
                          </Badge>
                        )}
                      </div>
                    </div>
                    <CardDescription>
                      <div className="flex items-center space-x-4 text-sm">
                        <span>📍 {alert.location}</span>
                        <span>🕐 {alert.timestamp}</span>
                      </div>
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="flex justify-end space-x-2">
                      <Button variant="outline" size="sm">
                        <Icon name="Eye" className="h-4 w-4 mr-2" />
                        Подробности
                      </Button>
                      {alert.status === 'active' && (
                        <Button size="sm">
                          <Icon name="Check" className="h-4 w-4 mr-2" />
                          Подтвердить
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          {/* External Notifications */}
          <TabsContent value="notifications" className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-bold text-gray-900">
                Внешние уведомления
              </h2>
              <Button>
                <Icon name="Plus" className="h-4 w-4 mr-2" />
                Новый канал
              </Button>
            </div>

            <div className="grid gap-4">
              {notifications.map((channel) => (
                <Card key={channel.id}>
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <Icon name={
                          channel.type === 'telegram' ? 'MessageCircle' :
                          channel.type === 'sms' ? 'Phone' :
                          channel.type === 'email' ? 'Mail' : 'Webhook'
                        } className="h-5 w-5 text-primary" />
                        <CardTitle className="text-lg">{channel.name}</CardTitle>
                      </div>
                      <div className="flex items-center space-x-2">
                        <Badge className={getNotificationStatusColor(channel.status)}>
                          {channel.status}
                        </Badge>
                        <Badge variant="outline" className="capitalize">
                          {channel.type}
                        </Badge>
                      </div>
                    </div>
                    <CardDescription>
                      Последнее использование: {channel.lastUsed}
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-2">
                      {channel.config.recipients && (
                        <div>
                          <span className="text-sm font-medium text-gray-600">Получатели:</span>
                          <div className="flex flex-wrap gap-1 mt-1">
                            {channel.config.recipients.map((recipient, index) => (
                              <Badge key={index} variant="secondary" className="text-xs">
                                {recipient}
                              </Badge>
                            ))}
                          </div>
                        </div>
                      )}
                      {channel.config.endpoint && (
                        <div>
                          <span className="text-sm font-medium text-gray-600">Endpoint:</span>
                          <code className="ml-2 text-xs bg-gray-100 px-2 py-1 rounded">
                            {channel.config.endpoint}
                          </code>
                        </div>
                      )}
                    </div>
                    <div className="flex justify-end space-x-2 mt-4">
                      <Button variant="outline" size="sm">
                        <Icon name="Settings" className="h-4 w-4 mr-2" />
                        Настроить
                      </Button>
                      <Button variant="outline" size="sm">
                        <Icon name="Send" className="h-4 w-4 mr-2" />
                        Тест
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          {/* Machine Learning Predictions */}
          <TabsContent value="ml" className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-bold text-gray-900">
                Машинное обучение и прогнозы
              </h2>
              <Button>
                <Icon name="RefreshCw" className="h-4 w-4 mr-2" />
                Обновить модель
              </Button>
            </div>

            <div className="grid gap-4">
              {mlPredictions.map((prediction) => (
                <Card key={prediction.id} className="border-l-4 border-l-purple-500">
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <Icon name="Brain" className="h-5 w-5 text-purple-600" />
                        <CardTitle className="text-lg">{prediction.prediction}</CardTitle>
                      </div>
                      <div className="flex items-center space-x-2">
                        <Badge variant="outline" className="capitalize">
                          {prediction.type.replace('_', ' ')}
                        </Badge>
                        <Badge className={`${getConfidenceColor(prediction.confidence)} bg-opacity-10`}>
                          {prediction.confidence}% точность
                        </Badge>
                      </div>
                    </div>
                    <CardDescription>
                      Прогноз на: {prediction.timeframe} | Создан: {prediction.createdAt}
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      <div>
                        <span className="text-sm font-medium text-gray-600">Ключевые факторы:</span>
                        <div className="flex flex-wrap gap-2 mt-2">
                          {prediction.factors.map((factor, index) => (
                            <Badge key={index} variant="secondary" className="text-xs">
                              {factor}
                            </Badge>
                          ))}
                        </div>
                      </div>
                      <div className="flex justify-end space-x-2">
                        <Button variant="outline" size="sm">
                          <Icon name="TrendingUp" className="h-4 w-4 mr-2" />
                          Детали анализа
                        </Button>
                        <Button size="sm">
                          <Icon name="AlertTriangle" className="h-4 w-4 mr-2" />
                          Создать задачу
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          {/* Integrations */}
          <TabsContent value="integrations" className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-bold text-gray-900">
                Интеграции с корпоративными системами
              </h2>
              <Button>
                <Icon name="Plus" className="h-4 w-4 mr-2" />
                Новая интеграция
              </Button>
            </div>

            <div className="grid gap-4">
              {integrations.map((integration) => (
                <Card key={integration.id}>
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <Icon name={
                          integration.type === '1c' ? 'Database' :
                          integration.type === 'sap' ? 'Building' :
                          integration.type === 'erp' ? 'Factory' : 'Globe'
                        } className="h-5 w-5 text-primary" />
                        <CardTitle className="text-lg">{integration.name}</CardTitle>
                      </div>
                      <div className="flex items-center space-x-2">
                        <Badge className={getIntegrationStatusColor(integration.status)}>
                          {integration.status}
                        </Badge>
                        <Badge variant="outline" className="uppercase">
                          {integration.type}
                        </Badge>
                      </div>
                    </div>
                    <CardDescription>
                      Последняя синхронизация: {integration.lastSync}
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-4">
                        <div className="text-center">
                          <div className="text-2xl font-bold text-primary">{integration.dataExchanged}</div>
                          <div className="text-xs text-gray-500">Записей обменяно</div>
                        </div>
                        {integration.status === 'syncing' && (
                          <div className="flex items-center space-x-2">
                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-primary"></div>
                            <span className="text-sm text-blue-600">Синхронизация...</span>
                          </div>
                        )}
                      </div>
                      <div className="flex space-x-2">
                        <Button variant="outline" size="sm">
                          <Icon name="Settings" className="h-4 w-4 mr-2" />
                          Настроить
                        </Button>
                        <Button variant="outline" size="sm">
                          <Icon name="RefreshCw" className="h-4 w-4 mr-2" />
                          Синхронизировать
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          {/* User Roles */}
          <TabsContent value="roles" className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-bold text-gray-900">
                Управление ролями и доступом
              </h2>
              <Button>
                <Icon name="Plus" className="h-4 w-4 mr-2" />
                Создать роль
              </Button>
            </div>

            <div className="grid gap-4">
              {userRoles.map((role) => (
                <Card key={role.id}>
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <Icon name="Shield" className="h-5 w-5 text-primary" />
                        <CardTitle className="text-lg">{role.name}</CardTitle>
                      </div>
                      <Badge variant="outline" className="capitalize">
                        {role.level}
                      </Badge>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      <div>
                        <span className="text-sm font-medium text-gray-600">Права доступа:</span>
                        <div className="flex flex-wrap gap-1 mt-1">
                          {role.permissions.map((permission, index) => (
                            <Badge key={index} variant="secondary" className="text-xs">
                              {permission.replace('_', ' ')}
                            </Badge>
                          ))}
                        </div>
                      </div>
                      <div>
                        <span className="text-sm font-medium text-gray-600">Доступные виджеты:</span>
                        <div className="flex flex-wrap gap-1 mt-1">
                          {role.dashboardConfig.widgets.map((widget, index) => (
                            <Badge key={index} variant="outline" className="text-xs">
                              {widget}
                            </Badge>
                          ))}
                        </div>
                      </div>
                      <div className="flex justify-between items-center">
                        <div>
                          <span className="text-sm font-medium text-gray-600">Уровень алертов: </span>
                          <Badge className={role.dashboardConfig.alertLevel === 'all' ? 'bg-blue-100 text-blue-800' : 'bg-orange-100 text-orange-800'}>
                            {role.dashboardConfig.alertLevel}
                          </Badge>
                        </div>
                        <div className="flex space-x-2">
                          <Button variant="outline" size="sm">
                            <Icon name="Edit" className="h-4 w-4 mr-2" />
                            Редактировать
                          </Button>
                          <Button variant="outline" size="sm">
                            <Icon name="Users" className="h-4 w-4 mr-2" />
                            Назначить пользователям
                          </Button>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          {/* Analytics */}
          <TabsContent value="analytics" className="space-y-4">
            <h2 className="text-2xl font-bold text-gray-900">
              Интеллектуальная аналитика
            </h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Тренды безопасности</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="flex justify-between items-center">
                      <span className="text-sm text-gray-600">Январь 2024</span>
                      <div className="flex items-center space-x-2">
                        <Progress value={94} className="w-20" />
                        <span className="text-sm font-medium">94%</span>
                        <Icon name="TrendingUp" className="h-4 w-4 text-green-600" />
                      </div>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-sm text-gray-600">Декабрь 2023</span>
                      <div className="flex items-center space-x-2">
                        <Progress value={89} className="w-20" />
                        <span className="text-sm font-medium">89%</span>
                        <Icon name="TrendingUp" className="h-4 w-4 text-green-600" />
                      </div>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-sm text-gray-600">Ноябрь 2023</span>
                      <div className="flex items-center space-x-2">
                        <Progress value={78} className="w-20" />
                        <span className="text-sm font-medium">78%</span>
                        <Icon name="TrendingDown" className="h-4 w-4 text-red-600" />
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Эффективность АСУБТ</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    <div className="flex justify-between items-center">
                      <span className="text-sm">Автоматических проверок</span>
                      <Badge variant="outline">1,247</Badge>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-sm">Предотвращенных инцидентов</span>
                      <Badge variant="outline">89</Badge>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-sm">Время реакции (сек)</span>
                      <Badge variant="outline">2.3</Badge>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-sm">Точность прогнозов</span>
                      <Badge variant="outline">96.7%</Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          {/* Backup & Recovery */}
          <TabsContent value="backup" className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-bold text-gray-900">
                Резервное копирование и восстановление
              </h2>
              <div className="flex space-x-2">
                <Button variant="outline">
                  <Icon name="Plus" className="h-4 w-4 mr-2" />
                  Создать бэкап
                </Button>
                <Button>
                  <Icon name="RotateCcw" className="h-4 w-4 mr-2" />
                  Восстановить
                </Button>
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Backup Configurations */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-semibold">Конфигурации бэкапов</h3>
                  <div className="text-sm text-gray-600">
                    Общий размер: {getTotalBackupSize()}
                  </div>
                </div>
                {backupConfigs.map((config) => (
                  <Card key={config.id}>
                    <CardHeader>
                      <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-3">
                          <Icon name={
                            config.type === 'full' ? 'Database' :
                            config.type === 'incremental' ? 'GitBranch' : 'GitMerge'
                          } className="h-5 w-5 text-primary" />
                          <CardTitle className="text-base">{config.name}</CardTitle>
                        </div>
                        <div className="flex items-center space-x-2">
                          <Badge className={getBackupStatusColor(config.status)}>
                            {config.status}
                          </Badge>
                          <Badge variant="outline" className="capitalize">
                            {config.type}
                          </Badge>
                        </div>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-2 text-sm">
                        <div className="flex justify-between">
                          <span className="text-gray-600">Расписание:</span>
                          <span className="font-medium">{config.schedule}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Последний:</span>
                          <span>{config.lastBackup}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Следующий:</span>
                          <span>{config.nextBackup}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Размер:</span>
                          <span className="font-medium">{config.size}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Хранение:</span>
                          <span>{config.retention} дней</span>
                        </div>
                      </div>
                      <div className="flex justify-end space-x-2 mt-4">
                        <Button variant="outline" size="sm">
                          <Icon name="Settings" className="h-4 w-4 mr-2" />
                          Настроить
                        </Button>
                        <Button variant="outline" size="sm">
                          <Icon name="Play" className="h-4 w-4 mr-2" />
                          Запустить
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>

              {/* Restore Points */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold">Точки восстановления</h3>
                {restorePoints.map((point) => (
                  <Card key={point.id}>
                    <CardHeader>
                      <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-3">
                          <Icon name={
                            point.type === 'manual' ? 'User' :
                            point.type === 'automatic' ? 'Clock' : 'AlertTriangle'
                          } className="h-5 w-5 text-primary" />
                          <CardTitle className="text-base">{point.name}</CardTitle>
                        </div>
                        <div className="flex items-center space-x-2">
                          <Badge className={getIntegrityColor(point.integrity)}>
                            {point.integrity}
                          </Badge>
                          <Badge variant="outline" className="capitalize">
                            {point.type}
                          </Badge>
                        </div>
                      </div>
                      <CardDescription className="text-sm">
                        {point.description}
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-2 text-sm">
                        <div className="flex justify-between">
                          <span className="text-gray-600">Создан:</span>
                          <span>{point.createdAt}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Размер:</span>
                          <span className="font-medium">{point.size}</span>
                        </div>
                        <div>
                          <span className="text-sm text-gray-600">Типы данных:</span>
                          <div className="flex flex-wrap gap-1 mt-1">
                            {point.dataTypes.map((type, index) => (
                              <Badge key={index} variant="secondary" className="text-xs">
                                {type}
                              </Badge>
                            ))}
                          </div>
                        </div>
                      </div>
                      <div className="flex justify-end space-x-2 mt-4">
                        <Button variant="outline" size="sm">
                          <Icon name="Eye" className="h-4 w-4 mr-2" />
                          Подробности
                        </Button>
                        {point.integrity === 'verified' && (
                          <Button size="sm">
                            <Icon name="RotateCcw" className="h-4 w-4 mr-2" />
                            Восстановить
                          </Button>
                        )}
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
          </TabsContent>

          {/* Security Audit */}
          <TabsContent value="audit" className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-bold text-gray-900">
                Аудит безопасности и мониторинг целостности
              </h2>
              <div className="flex space-x-2">
                <Button variant="outline">
                  <Icon name="Play" className="h-4 w-4 mr-2" />
                  Запустить аудит
                </Button>
                <Button>
                  <Icon name="FileText" className="h-4 w-4 mr-2" />
                  Отчет
                </Button>
              </div>
            </div>

            {/* System Health Overview */}
            <Card>
              <CardHeader>
                <CardTitle>Общее состояние системы</CardTitle>
                <CardDescription>
                  Оценка здоровья: {getSystemHealthScore()}% | Последняя проверка: {new Date().toLocaleString('ru-RU')}
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  {systemIntegrity.map((component) => (
                    <div key={component.id} className="p-4 border rounded-lg">
                      <div className="flex items-center justify-between mb-2">
                        <span className="font-medium text-sm">{component.component}</span>
                        <Badge className={getSystemStatusColor(component.status)}>
                          {component.status}
                        </Badge>
                      </div>
                      <div className="space-y-2 text-xs text-gray-600">
                        <div className="flex justify-between">
                          <span>Uptime:</span>
                          <span className="font-medium">{component.uptime}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Производительность:</span>
                          <span className="font-medium">{component.performance}%</span>
                        </div>
                        <Progress value={component.performance} className="h-1" />
                        {component.issues.length > 0 && (
                          <div className="text-red-600 text-xs">
                            {component.issues.length} проблем
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Security Audits */}
            <div className="space-y-4">
              <h3 className="text-lg font-semibold">История аудитов безопасности</h3>
              {securityAudits.map((audit) => (
                <Card key={audit.id}>
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <Icon name="ShieldCheck" className="h-5 w-5 text-primary" />
                        <CardTitle className="text-lg">{audit.title}</CardTitle>
                      </div>
                      <div className="flex items-center space-x-2">
                        <Badge className={getAuditStatusColor(audit.status)}>
                          {audit.status}
                        </Badge>
                        <Badge className={getSeverityColor(audit.severity)}>
                          {audit.severity}
                        </Badge>
                        <Badge variant="outline" className="capitalize">
                          {audit.type.replace('_', ' ')}
                        </Badge>
                      </div>
                    </div>
                    <CardDescription>
                      Начат: {audit.startTime} {audit.endTime && `| Завершен: ${audit.endTime}`}
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-3 gap-4 mb-4">
                      <div className="text-center p-3 bg-red-50 rounded-lg">
                        <div className="text-2xl font-bold text-red-600">{audit.findings.issues}</div>
                        <div className="text-xs text-red-600">Проблемы</div>
                      </div>
                      <div className="text-center p-3 bg-yellow-50 rounded-lg">
                        <div className="text-2xl font-bold text-yellow-600">{audit.findings.warnings}</div>
                        <div className="text-xs text-yellow-600">Предупреждения</div>
                      </div>
                      <div className="text-center p-3 bg-green-50 rounded-lg">
                        <div className="text-2xl font-bold text-green-600">{audit.findings.passed}</div>
                        <div className="text-xs text-green-600">Пройдено</div>
                      </div>
                    </div>
                    
                    {audit.recommendations.length > 0 && (
                      <div className="space-y-2">
                        <span className="text-sm font-medium text-gray-600">Рекомендации:</span>
                        <ul className="space-y-1">
                          {audit.recommendations.map((rec, index) => (
                            <li key={index} className="text-sm text-gray-700 flex items-start space-x-2">
                              <Icon name="ArrowRight" className="h-3 w-3 mt-0.5 text-gray-400" />
                              <span>{rec}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                    
                    <div className="flex justify-end space-x-2 mt-4">
                      <Button variant="outline" size="sm">
                        <Icon name="Download" className="h-4 w-4 mr-2" />
                        Скачать отчет
                      </Button>
                      {audit.status === 'completed' && (
                        <Button variant="outline" size="sm">
                          <Icon name="RefreshCw" className="h-4 w-4 mr-2" />
                          Повторить аудит
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
};

export default Index;